# docker-compose.dev.yml
version: '3.8'
services:
  jadwal-sholat-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${DEV_PORT:-3000}:3000"
      - "${DEV_WS_PORT:-3001}:3001"  # Hot reload websocket
    volumes:
      # Bind mount untuk development
      - ./src:/app/src:rw
      - ./public:/app/public:rw
      - ./index.html:/app/index.html:rw
      - ./package.json:/app/package.json:rw
      - ./package-lock.json:/app/package-lock.json:rw
      - ./tailwind.config.js:/app/tailwind.config.js:rw
      - ./postcss.config.js:/app/postcss.config.js:rw
      - ./vite.config.js:/app/vite.config.js:rw
      # Persistent volumes
      - ./volumes/node_modules:/app/node_modules:rw
      - ./volumes/cache:/app/.cache:rw
      - ./volumes/build:/app/build:rw
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Jakarta
      - VITE_API_ALADHAN=https://api.aladhan.com/v1
      - VITE_API_MYQURAN=https://api.myquran.com/v2
      - VITE_API_IPGEOLOCATION=https://api.ipgeolocation.io/ipgeo
    command: npm run dev
    stdin_open: true
    tty: true
    networks:
      - jadwal-sholat-dev-network

networks:
  jadwal-sholat-dev-network:
    driver: bridge
